import type {Metadata} from 'next';
import {Gilroy_Medium, Gilroy_ExtraBold} from '@/app/ui/fonts';
import '@/app/ui/globals.css';
import Navbar from './ui/Nav/Navbar';
import Footer from './ui/Footer/Index';

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={`${Gilroy_Medium.variable} ${Gilroy_ExtraBold.variable} antialiased`}
			>
				<Navbar />
				{children}
				<Footer />
			</body>
		</html>
	);
}
